services:
  busybox-builder:
    build: .
    image: busybox-builder:latest
    container_name: busybox-builder
    stdin_open: true
    tty: true
    volumes:
      - ./output:/output
      - ./workspace:/workspace
    working_dir: /workspace

